version: '3.8'

services:
  # Development service
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5000
    command: npm run dev
    stdin_open: true
    tty: true
    networks:
      - app-network

  # Production service
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  # Optional: Mock API service for development
  # api-mock:
  #   image: stoplight/prism:4
  #   ports:
  #     - "5000:4010"
  #   command: mock -h 0.0.0.0 /tmp/api.yaml
  #   volumes:
  #     - ./api-spec.yaml:/tmp/api.yaml:ro
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
    driver: local